name       : python-jdcal
version    : 1.4.1
release    : 1
homepage   : https://github.com/phn/jdcal
source     :
    - https://github.com/phn/jdcal/archive/v1.4.1.tar.gz : 6cb87959fb9293bdd577967419af735a1a0aee3ce778c443acb219b2668c6597
license    : BSD-2-Clause
component  : programming.python
summary    : This module contains functions for converting between Julian dates and calendar dates.
description: |
    A function for converting Gregorian calendar dates to Julian dates, and another function for converting Julian calendar dates to Julian dates are defined. Two functions for the reverse calculations are also defined.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
